name = "Libwebsockets"
uuid = "30a1cee6-c274-443c-b274-d8ea34e8f87d"
version = "1.1.0"

[deps]
libwebsockets_jll = "b6b84edf-6aef-5ff6-9b66-656961a84a09"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
libwebsockets_jll = "4.3.4"
julia = "1.8"
